### ISSUE TITLE
remove plugins from repo

### ISSUE THREAD

**Issue by carmona** [mario-aleo/cordova-angular-angularMaterial-seed#3]
Since cordova plugins are available through public registry, they should be listed in config.xml file, and not uploaded to git repository.

This can be accomplished by using the save flag as in  `cordova plugins install barcodeScanner --save` when installing plugins so they get saved to config.xml and when people clone this repo they just have to run `cordova prepare` so the plugins are locally downloaded.

**Comment by mario-aleo** [comment]
Awesome, that's a really perfect way, I'll make this changes when I get home tonight.

**Comment by carmona** [comment]
great! don't forget to add 'plugins/' to your gitignore file
